version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "typeorm_db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "root"
      # You can use whatever password you like
      MYSQL_PASSWORD: "Erepoc69!"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "Erepoc69!"
    ports:
      - "3306:3306"
    volumes:
      - my-db-mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
volumes:
  my-db-mysql:
